### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by bachwebsite** [titaniumnetwork-dev/Ultraviolet-Static#13]
register-sw.js:33 Uncaught (in promise) ReferenceError: BareMux is not defined
    at registerSW (register-sw.js:33:3)
    at async HTMLFormElement.<anonymous> (index.js:27:5)

**Comment by NuperSTAR** [comment]
Create a new folder called "baremux" and insert the baremux file called "bare.cjs." You could get it from here: https://github.com/MercuryWorkshop/bare-mux/releases/
